import React from 'react';
import { useCallback } from 'react';
import {View, Text, FlatList, StyleSheet} from 'react-native';
import { useFocusEffect } from '@react-navigation/native';
import { BackHandler } from 'react-native';

const data = [
  {
    ID: 595,
    MCC_Code: 9405,
    Category: 'Government Services, Intra',
    Sub_Category: 'Government Purchases, Government Only',
    Is_Seller_Accepted: true,
  },
  {
    ID: 598,
    MCC_Code: 9402,
    Category: 'Others',
    Sub_Category: 'Postal services government only',
    Is_Seller_Accepted: true,
  },
  {
    ID: 600,
    MCC_Code: 9400,
    Category: 'Others',
    Sub_Category: 'PMNRF',
    Is_Seller_Accepted: true,
  },
  {
    ID: 689,
    MCC_Code: 9311,
    Category: 'Tax Payment',
    Sub_Category: 'Tax payments',
    Is_Seller_Accepted: true,
  },
  {
    ID: 777,
    MCC_Code: 9223,
    Category: 'Others',
    Sub_Category: 'Bail and bond payments',
    Is_Seller_Accepted: true,
  },
  {
    ID: 778,
    MCC_Code: 9222,
    Category: 'Others',
    Sub_Category: 'Fines',
    Is_Seller_Accepted: true,
  },
  {
    ID: 789,
    MCC_Code: 9211,
    Category: 'Others',
    Sub_Category: 'Court costs, including alimony and child support',
    Is_Seller_Accepted: true,
  },
  {
    ID: 1069,
    MCC_Code: 8931,
    Category: 'Others',
    Sub_Category: 'Accounting, auditing and bookkeeping services',
    Is_Seller_Accepted: true,
  },
  {
    ID: 1089,
    MCC_Code: 8911,
    Category: 'Others',
    Sub_Category: 'Architectural, engineering and surveying services',
    Is_Seller_Accepted: true,
  },
  {
    ID: 1266,
    MCC_Code: 8734,
    Category: 'Others',
    Sub_Category: 'Testing laboratories (non-medical)',
    Is_Seller_Accepted: true,
  },
  {
    ID: 1325,
    MCC_Code: 8675,
    Category: 'Others',
    Sub_Category: 'Automobile associations',
    Is_Seller_Accepted: true,
  },
  {
    ID: 1339,
    MCC_Code: 8661,
    Category: 'Others',
    Sub_Category: 'Religious organizations',
    Is_Seller_Accepted: true,
  },
  {
    ID: 1349,
    MCC_Code: 8651,
    Category: 'Others',
    Sub_Category: 'Political organizations',
    Is_Seller_Accepted: true,
  },
  {
    ID: 1359,
    MCC_Code: 8641,
    Category: 'Others',
    Sub_Category: 'Civic, social and fraternal associations',
    Is_Seller_Accepted: true,
  },
  {
    ID: 1507,
    MCC_Code: 8493,
    Category: 'Vaccine voucher',
    Sub_Category: '',
    Is_Seller_Accepted: true,
  },
  {
    ID: 1602,
    MCC_Code: 8398,
    Category: 'Others',
    Sub_Category: 'Charitable and social service organizations',
    Is_Seller_Accepted: true,
  },
  {
    ID: 1649,
    MCC_Code: 8351,
    Category: 'Others',
    Sub_Category: 'Child care services',
    Is_Seller_Accepted: true,
  },
  {
    ID: 1751,
    MCC_Code: 8249,
    Category: 'Education',
    Sub_Category: 'Trade and vocational schools',
    Is_Seller_Accepted: true,
  },
  {
    ID: 1756,
    MCC_Code: 8244,
    Category: 'Education',
    Sub_Category: 'Business and secretarial schools',
    Is_Seller_Accepted: true,
  },
  {
    ID: 1759,
    MCC_Code: 8241,
    Category: 'Education',
    Sub_Category: 'Correspondence schools',
    Is_Seller_Accepted: true,
  },
  {
    ID: 1780,
    MCC_Code: 8220,
    Category: 'Education',
    Sub_Category: 'College/University',
    Is_Seller_Accepted: true,
  },
  {
    ID: 1789,
    MCC_Code: 8211,
    Category: 'Education',
    Sub_Category: 'School',
    Is_Seller_Accepted: true,
  },
  {
    ID: 1889,
    MCC_Code: 8111,
    Category: 'Others',
    Sub_Category: 'Legal services and attorneys',
    Is_Seller_Accepted: true,
  },
  {
    ID: 1929,
    MCC_Code: 8071,
    Category: 'Others',
    Sub_Category: 'Medical and dental laboratories',
    Is_Seller_Accepted: true,
  },
  {
    ID: 1938,
    MCC_Code: 8062,
    Category: 'Hospital',
    Sub_Category: 'Hospitals',
    Is_Seller_Accepted: true,
  },
  {
    ID: 1950,
    MCC_Code: 8050,
    Category: 'Others',
    Sub_Category: 'Nursing and personal care facilities',
    Is_Seller_Accepted: true,
  },
  {
    ID: 1951,
    MCC_Code: 8049,
    Category: 'Others',
    Sub_Category: 'Podiatrists and chiropodists',
    Is_Seller_Accepted: true,
  },
  {
    ID: 1957,
    MCC_Code: 8043,
    Category: 'Others',
    Sub_Category: 'Opticians, optical goods and eyeglasses',
    Is_Seller_Accepted: true,
  },
  {
    ID: 1958,
    MCC_Code: 8042,
    Category: 'Others',
    Sub_Category: '',
    Is_Seller_Accepted: true,
  },
  {
    ID: 1959,
    MCC_Code: 8041,
    Category: 'Others',
    Sub_Category: '',
    Is_Seller_Accepted: true,
  },
  {
    ID: 1969,
    MCC_Code: 8031,
    Category: 'Others',
    Sub_Category: 'Osteopaths',
    Is_Seller_Accepted: true,
  },
  {
    ID: 1979,
    MCC_Code: 8021,
    Category: 'Others',
    Sub_Category: 'Dentists and orthodontists',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2002,
    MCC_Code: 7998,
    Category: 'Others',
    Sub_Category: 'Aquariums, seaquariums and dolphinariums',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2003,
    MCC_Code: 7997,
    Category: 'Others',
    Sub_Category:
      'Membership clubs (sports, recreation, athletic), country clubs and private golf courses',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2004,
    MCC_Code: 7996,
    Category: 'Entertainment',
    Sub_Category: 'Exhibition/Events/Theme Park',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2006,
    MCC_Code: 7994,
    Category: 'Entertainment',
    Sub_Category: 'Gaming Zone',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2007,
    MCC_Code: 7993,
    Category: 'Others',
    Sub_Category: 'Video amusement game supplies',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2008,
    MCC_Code: 7992,
    Category: 'Others',
    Sub_Category: 'Public golf courses',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2009,
    MCC_Code: 7991,
    Category: 'Others',
    Sub_Category: 'Tourist attractions and exhibits',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2059,
    MCC_Code: 7941,
    Category: 'Others',
    Sub_Category:
      'Commercial sports, professional sports clubs, athletic fields and sports promoters',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2067,
    MCC_Code: 7933,
    Category: 'Others',
    Sub_Category: 'Bowling alleys',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2068,
    MCC_Code: 7932,
    Category: 'Others',
    Sub_Category: 'Billiard and pool establishments',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2078,
    MCC_Code: 7922,
    Category: 'Others',
    Sub_Category:
      'Theatrical producers (except motion pictures) and ticket agencies',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2089,
    MCC_Code: 7911,
    Category: 'Others',
    Sub_Category: 'Dance halls, studios and schools',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2159,
    MCC_Code: 7841,
    Category: 'Others',
    Sub_Category: 'Video tape rentals',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2168,
    MCC_Code: 7832,
    Category: 'Entertainment',
    Sub_Category: 'Cinema Hall/Multiplex',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2171,
    MCC_Code: 7829,
    Category: 'Others',
    Sub_Category: 'Motion picture and video tape production and distribution',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2308,
    MCC_Code: 7692,
    Category: 'Others',
    Sub_Category: 'Welding services',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2359,
    MCC_Code: 7641,
    Category: 'Others',
    Sub_Category: 'Furniture reupholstery, repair and refinishing',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2369,
    MCC_Code: 7631,
    Category: 'Others',
    Sub_Category: 'Watch, clock and jewellery repair shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2371,
    MCC_Code: 7629,
    Category: 'Others',
    Sub_Category: 'Electrical and small appliance repair shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2377,
    MCC_Code: 7623,
    Category: 'Others',
    Sub_Category: 'Air conditioning and refrigeration repair shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2378,
    MCC_Code: 7622,
    Category: 'Others',
    Sub_Category: 'Electronics repair shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2451,
    MCC_Code: 7549,
    Category: 'Others',
    Sub_Category: 'Towing services',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2458,
    MCC_Code: 7542,
    Category: 'Others',
    Sub_Category: 'Car washes',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2462,
    MCC_Code: 7538,
    Category: 'Others',
    Sub_Category: 'Automotive service shops (non-dealer)',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2465,
    MCC_Code: 7535,
    Category: 'Others',
    Sub_Category: 'Automotive paint shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2466,
    MCC_Code: 7534,
    Category: 'Others',
    Sub_Category: 'Tyre retreading and repair shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2469,
    MCC_Code: 7531,
    Category: 'Others',
    Sub_Category: 'Automotive body repair shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2477,
    MCC_Code: 7523,
    Category: 'Others',
    Sub_Category: 'Parking lots and garages',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2481,
    MCC_Code: 7519,
    Category: 'Others',
    Sub_Category: 'Motor home and recreational vehicle rentals',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2487,
    MCC_Code: 7513,
    Category: 'Others',
    Sub_Category: 'Truck and utility trailer rentals',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2488,
    MCC_Code: 7512,
    Category: 'Travel',
    Sub_Category: 'Rental Car',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2591,
    MCC_Code: 7409,
    Category: 'Digital Account Opening',
    Sub_Category: '',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2592,
    MCC_Code: 7408,
    Category: 'Entities Facilitating P2P Lending',
    Sub_Category: '',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2593,
    MCC_Code: 7407,
    Category: 'P2PM CHANGES',
    Sub_Category: '',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2605,
    MCC_Code: 7395,
    Category: 'Others',
    Sub_Category: 'Photofinishing laboratories and photo developing',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2606,
    MCC_Code: 7394,
    Category: 'Others',
    Sub_Category:
      'Equipment, tool, furniture and appliance rentals and leasing',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2607,
    MCC_Code: 7393,
    Category: 'Others',
    Sub_Category:
      'Detective agencies, protective agencies and security services, including armoured cars and guard dogs',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2608,
    MCC_Code: 7392,
    Category: 'Others',
    Sub_Category: 'Management, consulting and public relations services',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2625,
    MCC_Code: 7375,
    Category: 'Others',
    Sub_Category: 'Information retrieval services',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2628,
    MCC_Code: 7372,
    Category: 'Others',
    Sub_Category:
      'Computer programming, data processing and integrated systems design services',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2639,
    MCC_Code: 7361,
    Category: 'Others',
    Sub_Category: 'Employment agencies and temporary help services',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2651,
    MCC_Code: 7349,
    Category: 'Others',
    Sub_Category: 'Cleaning, maintenance and janitorial services',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2658,
    MCC_Code: 7342,
    Category: 'Others',
    Sub_Category: 'Exterminating and disinfecting services',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2661,
    MCC_Code: 7339,
    Category: 'Others',
    Sub_Category: 'Stenographic and secretarial support services',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2662,
    MCC_Code: 7338,
    Category: 'Others',
    Sub_Category: 'Quick copy, reproduction and blueprinting services',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2667,
    MCC_Code: 7333,
    Category: 'Others',
    Sub_Category: 'Commercial photography, art and graphics',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2668,
    MCC_Code: 7332,
    Category: 'Retail Shopping',
    Sub_Category: 'Blueprinting/Photocopy Services',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2678,
    MCC_Code: 7322,
    Category: 'Wholesale/Dealer/B2B',
    Sub_Category: 'Wholesale/Dealer/B2B',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2679,
    MCC_Code: 7321,
    Category: 'Others',
    Sub_Category: 'Consumer credit reporting agencies',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2689,
    MCC_Code: 7311,
    Category: 'Others',
    Sub_Category: 'Advertising services',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2702,
    MCC_Code: 7298,
    Category: 'Beauty/Wellness',
    Sub_Category: 'Health and Beauty Spa',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2703,
    MCC_Code: 7297,
    Category: 'Others',
    Sub_Category: 'Massage parlours',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2704,
    MCC_Code: 7296,
    Category: 'Others',
    Sub_Category: 'Clothing rentals costumes, uniforms and formal wear',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2722,
    MCC_Code: 7278,
    Category: 'Others',
    Sub_Category: 'Buying and shopping services and clubs',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2723,
    MCC_Code: 7277,
    Category: 'Others',
    Sub_Category: 'Counselling services debt, marriage and personal',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2724,
    MCC_Code: 7276,
    Category: 'Others',
    Sub_Category: 'Tax preparation services',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2727,
    MCC_Code: 7273,
    Category: 'Others',
    Sub_Category: 'Dating and escort services',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2739,
    MCC_Code: 7261,
    Category: 'Others',
    Sub_Category: 'Funeral services and crematoriums',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2749,
    MCC_Code: 7251,
    Category: 'Others',
    Sub_Category:
      'Shoe repair shops, shoe shine parlours and hat cleaning shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2770,
    MCC_Code: 7230,
    Category: 'Others',
    Sub_Category: 'Beauty and barber shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2779,
    MCC_Code: 7221,
    Category: 'Others',
    Sub_Category: 'Photographic studios',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2783,
    MCC_Code: 7217,
    Category: 'Others',
    Sub_Category: 'Carpet and upholstery cleaning',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2784,
    MCC_Code: 7216,
    Category: 'Others',
    Sub_Category: 'Dry cleaners',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2789,
    MCC_Code: 7211,
    Category: 'Others',
    Sub_Category: 'Laundry services family and commercial',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2790,
    MCC_Code: 7210,
    Category: 'Others',
    Sub_Category: 'Laundry, cleaning and garment services',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2967,
    MCC_Code: 7033,
    Category: 'Others',
    Sub_Category: 'Trailer parks and camp-sites',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2968,
    MCC_Code: 7032,
    Category: 'Others',
    Sub_Category: 'Sporting and recreational camps',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2987,
    MCC_Code: 7013,
    Category: 'Small PPI wallet loading',
    Sub_Category: '',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2988,
    MCC_Code: 7012,
    Category: 'Others',
    Sub_Category: 'Timeshares',
    Is_Seller_Accepted: true,
  },
  {
    ID: 2989,
    MCC_Code: 7011,
    Category: 'Others',
    Sub_Category: 'Lodging hotels, motels and resorts',
    Is_Seller_Accepted: true,
  },
  {
    ID: 3334,
    MCC_Code: 6666,
    Category: 'International merchant services',
    Sub_Category: '',
    Is_Seller_Accepted: true,
  },
  {
    ID: 3460,
    MCC_Code: 6540,
    Category: 'Others',
    Sub_Category: 'Debit card to wallet credit (Wallet top up)',
    Is_Seller_Accepted: true,
  },
  {
    ID: 3487,
    MCC_Code: 6513,
    Category: 'Others',
    Sub_Category: 'Real Estate Agents and Managers - Rentals',
    Is_Seller_Accepted: true,
  },
  {
    ID: 3700,
    MCC_Code: 6300,
    Category: 'Insurance',
    Sub_Category: 'Insurance sales, underwriting and premiums',
    Is_Seller_Accepted: true,
  },
  {
    ID: 3789,
    MCC_Code: 6211,
    Category: 'Others',
    Sub_Category: 'Securities brokers and dealers',
    Is_Seller_Accepted: true,
  },
  {
    ID: 3949,
    MCC_Code: 6051,
    Category: 'Others',
    Sub_Category:
      'Non-financial institutions foreign currency, money orders (not wire transfer), scrip and travellers checks',
    Is_Seller_Accepted: true,
  },
  {
    ID: 3988,
    MCC_Code: 6012,
    Category: 'Others',
    Sub_Category: 'Financial institutions merchandise and services',
    Is_Seller_Accepted: true,
  },
  {
    ID: 3989,
    MCC_Code: 6011,
    Category: 'Others',
    Sub_Category: 'Financial institutions automated cash disbursements',
    Is_Seller_Accepted: true,
  },
  {
    ID: 3990,
    MCC_Code: 6010,
    Category: 'Others',
    Sub_Category: 'Financial institutions manual cash disbursements',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4002,
    MCC_Code: 5998,
    Category: 'Others',
    Sub_Category: 'Tent and awning shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4003,
    MCC_Code: 5997,
    Category: 'Others',
    Sub_Category: 'Electric razor outlets sales and service',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4004,
    MCC_Code: 5996,
    Category: 'Others',
    Sub_Category: 'Swimming pools sales, supplies and services',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4005,
    MCC_Code: 5995,
    Category: 'Others',
    Sub_Category: 'Pet shops, pet food and supplies',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4006,
    MCC_Code: 5994,
    Category: 'Others',
    Sub_Category: 'Newsagents and news-stands',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4007,
    MCC_Code: 5993,
    Category: 'Others',
    Sub_Category: 'Cigar shops and stands',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4008,
    MCC_Code: 5992,
    Category: 'Others',
    Sub_Category: '',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4017,
    MCC_Code: 5983,
    Category: 'Others',
    Sub_Category: 'Fuel dealers fuel oil, wood, coal and liquefied petroleum',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4022,
    MCC_Code: 5978,
    Category: 'Others',
    Sub_Category: 'Typewriter outlets sales, service and rentals',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4023,
    MCC_Code: 5977,
    Category: 'Others',
    Sub_Category: 'Cosmetic Stores',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4024,
    MCC_Code: 5976,
    Category: 'Others',
    Sub_Category: 'Orthopaedic goods and prosthetic devices',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4025,
    MCC_Code: 5975,
    Category: 'Others',
    Sub_Category: 'Hearing aids sales, service and supplies',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4027,
    MCC_Code: 5973,
    Category: 'Others',
    Sub_Category: 'Religious goods and shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4028,
    MCC_Code: 5972,
    Category: 'Others',
    Sub_Category: 'Stamp and coin shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4029,
    MCC_Code: 5971,
    Category: 'Others',
    Sub_Category: 'Art dealers and galleries',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4030,
    MCC_Code: 5970,
    Category: 'Others',
    Sub_Category: 'Artist supply and craft shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4032,
    MCC_Code: 5968,
    Category: 'Others',
    Sub_Category: 'Direct marketing continuity/subscription merchants',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4033,
    MCC_Code: 5967,
    Category: 'Others',
    Sub_Category: 'Direct marketing inbound telemarketing merchants',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4034,
    MCC_Code: 5966,
    Category: 'Others',
    Sub_Category: 'Direct marketing outbound telemarketing merchants',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4035,
    MCC_Code: 5965,
    Category: 'Others',
    Sub_Category: 'Direct marketing combination catalogue and retail merchants',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4036,
    MCC_Code: 5964,
    Category: 'Others',
    Sub_Category: 'Direct marketing catalogue merchants',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4037,
    MCC_Code: 5963,
    Category: 'Others',
    Sub_Category: 'Door-to-door sales',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4038,
    MCC_Code: 5962,
    Category: 'Others',
    Sub_Category: 'Telemarketing travel-related arrangement services',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4039,
    MCC_Code: 5961,
    Category: 'Others',
    Sub_Category: '',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4040,
    MCC_Code: 5960,
    Category: 'Insurance',
    Sub_Category: 'Direct marketing - insurance services',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4050,
    MCC_Code: 5950,
    Category: 'Others',
    Sub_Category: 'Glassware and crystal shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4051,
    MCC_Code: 5949,
    Category: 'Others',
    Sub_Category: 'Sewing, needlework, fabric and piece goods shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4052,
    MCC_Code: 5948,
    Category: 'Others',
    Sub_Category: 'Luggage and leather goods shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4053,
    MCC_Code: 5947,
    Category: 'Others',
    Sub_Category: 'Gift, card, novelty and souvenir shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4054,
    MCC_Code: 5946,
    Category: 'Others',
    Sub_Category: 'Camera and photographic supply shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4055,
    MCC_Code: 5945,
    Category: 'Others',
    Sub_Category: 'Hobby, toy and game shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4056,
    MCC_Code: 5944,
    Category: 'Others',
    Sub_Category: 'Jewellery, watch, clock and silverware shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4057,
    MCC_Code: 5943,
    Category: 'Others',
    Sub_Category: 'Stationery, office and school supply shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4058,
    MCC_Code: 5942,
    Category: 'Others',
    Sub_Category: 'Bookshops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4059,
    MCC_Code: 5941,
    Category: 'Others',
    Sub_Category: 'Sporting goods shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4060,
    MCC_Code: 5940,
    Category: 'Others',
    Sub_Category: 'Bicycle shops sales and service',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4063,
    MCC_Code: 5937,
    Category: 'Others',
    Sub_Category: 'Antique reproduction shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4065,
    MCC_Code: 5935,
    Category: 'Others',
    Sub_Category: 'Wrecking and salvage yards',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4067,
    MCC_Code: 5933,
    Category: 'Others',
    Sub_Category: 'Pawn shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4068,
    MCC_Code: 5932,
    Category: 'Others',
    Sub_Category: '',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4069,
    MCC_Code: 5931,
    Category: 'Others',
    Sub_Category: 'Used merchandise and second-hand shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4079,
    MCC_Code: 5921,
    Category: 'Others',
    Sub_Category: 'Package shops beer, wine and liquor',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4088,
    MCC_Code: 5912,
    Category: 'Retail Shopping',
    Sub_Category: 'Medicine Shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4168,
    MCC_Code: 5832,
    Category: 'Antique Shops – Sales, Repairs, and Restoration Services',
    Sub_Category: '',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4182,
    MCC_Code: 5818,
    Category: 'Others',
    Sub_Category: 'Digital Goods: Large Digital Goods Merchant',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4183,
    MCC_Code: 5817,
    Category: 'Others',
    Sub_Category: 'Digital Goods: Applications (Excludes Games)',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4184,
    MCC_Code: 5816,
    Category: 'Others',
    Sub_Category: 'Digital Goods: Games',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4185,
    MCC_Code: 5815,
    Category: 'Others',
    Sub_Category: 'Digital Goods: Media, Books, Movies, Music',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4186,
    MCC_Code: 5814,
    Category: 'Food & Beverages',
    Sub_Category: 'Juice Shop',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4187,
    MCC_Code: 5813,
    Category: 'Food & Beverages',
    Sub_Category: 'Bar/Pub',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4188,
    MCC_Code: 5812,
    Category: 'Food & Beverages',
    Sub_Category: 'Eating Places & Restaurants',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4189,
    MCC_Code: 5811,
    Category: 'Others',
    Sub_Category: 'Caterers',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4265,
    MCC_Code: 5735,
    Category: 'Others',
    Sub_Category: 'Record shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4266,
    MCC_Code: 5734,
    Category: 'Others',
    Sub_Category: 'Computer software outlets',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4267,
    MCC_Code: 5733,
    Category: 'Others',
    Sub_Category: 'Music shops musical instruments, pianos and sheet music',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4268,
    MCC_Code: 5732,
    Category: 'Electronics & Durables',
    Sub_Category: 'Electronic & Mobile Shop',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4278,
    MCC_Code: 5722,
    Category: 'Electronics & Durables',
    Sub_Category: 'Home Appliances',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4282,
    MCC_Code: 5718,
    Category: 'Others',
    Sub_Category: 'Fireplaces, fireplace screens and accessories shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4285,
    MCC_Code: 5715,
    Category: 'Others',
    Sub_Category: 'Alcoholic beverage wholesalers',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4286,
    MCC_Code: 5714,
    Category: 'Others',
    Sub_Category: 'Drapery, window covering and upholstery shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4287,
    MCC_Code: 5713,
    Category: 'Others',
    Sub_Category: 'Floor covering services',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4288,
    MCC_Code: 5712,
    Category: 'Retail Shopping',
    Sub_Category: 'Furniture Shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4302,
    MCC_Code: 5698,
    Category: 'Clothing Store',
    Sub_Category: 'Wig and toupee shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4303,
    MCC_Code: 5697,
    Category: 'Clothing Store',
    Sub_Category: 'Tailors, seamstresses, mending and alterations',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4309,
    MCC_Code: 5691,
    Category: 'Clothing Store',
    Sub_Category: 'Mens and womens clothing shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4319,
    MCC_Code: 5681,
    Category: 'Clothing Store',
    Sub_Category: 'Furriers and fur shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4339,
    MCC_Code: 5661,
    Category: 'Retail Shopping',
    Sub_Category: 'Shoe Shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4345,
    MCC_Code: 5655,
    Category: 'Retail Shopping',
    Sub_Category: 'Sports & Riding Apparel Shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4349,
    MCC_Code: 5651,
    Category: 'Retail Shopping',
    Sub_Category: 'Family Clothing Shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4359,
    MCC_Code: 5641,
    Category: 'Clothing Store',
    Sub_Category: 'Children’s and infants wear shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4369,
    MCC_Code: 5631,
    Category: 'Clothing Store',
    Sub_Category: 'Women’s accessory and speciality shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4379,
    MCC_Code: 5621,
    Category: 'Clothing Store',
    Sub_Category: 'Women’s ready-to-wear shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4389,
    MCC_Code: 5611,
    Category: 'Clothing Store',
    Sub_Category: 'Men’s and boys clothing and accessory shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4402,
    MCC_Code: 5598,
    Category: 'Retail',
    Sub_Category: 'Snowmobile dealers',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4408,
    MCC_Code: 5592,
    Category: 'Retail',
    Sub_Category: 'Motor home dealers',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4429,
    MCC_Code: 5571,
    Category: 'Automobile',
    Sub_Category: 'Motorcycle',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4439,
    MCC_Code: 5561,
    Category: 'Retail',
    Sub_Category: 'Camper, recreational and utility trailer dealers',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4449,
    MCC_Code: 5551,
    Category: 'Retail',
    Sub_Category: 'Boat dealers',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4458,
    MCC_Code: 5542,
    Category: 'Fuel',
    Sub_Category: 'Automated fuel dispensers',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4459,
    MCC_Code: 5541,
    Category: 'Fuel',
    Sub_Category: 'Service stations (with or without ancillary services)',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4467,
    MCC_Code: 5533,
    Category: 'Automobile',
    Sub_Category: 'Spare Parts/Accessories',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4468,
    MCC_Code: 5532,
    Category: 'Retail',
    Sub_Category: 'Automotive tyre outlets',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4469,
    MCC_Code: 5531,
    Category: 'Retail',
    Sub_Category: 'Auto and home supply outlets',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4479,
    MCC_Code: 5521,
    Category: 'Retail',
    Sub_Category:
      'Car and truck dealers (used only) sales, service, repairs, parts and leasing',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4489,
    MCC_Code: 5511,
    Category: 'Automobile',
    Sub_Category: 'Automobile Dealer/Repair/Service',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4538,
    MCC_Code: 5462,
    Category: 'Food & Beverages',
    Sub_Category: 'Bakery/Namkeen/Sweets',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4549,
    MCC_Code: 5451,
    Category: 'Dairy/Fresh Products',
    Sub_Category: 'Milk Booth/Dairy',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4559,
    MCC_Code: 5441,
    Category: 'Retail',
    Sub_Category: 'Candy, nut and confectionery shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4578,
    MCC_Code: 5422,
    Category: 'Retail',
    Sub_Category: 'Freezer and locker meat provisioners',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4587,
    MCC_Code: 5413,
    Category: 'Credit Card Bill Payments',
    Sub_Category: '',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4588,
    MCC_Code: 5412,
    Category: 'Purchase of digital gold',
    Sub_Category: '',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4589,
    MCC_Code: 5411,
    Category: 'Retail Shopping',
    Sub_Category: 'Grocery/Supermarket/Vegetables',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4689,
    MCC_Code: 5311,
    Category: 'Retail',
    Sub_Category: 'Department stores',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4690,
    MCC_Code: 5310,
    Category: 'Retail',
    Sub_Category: 'Discount shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4691,
    MCC_Code: 5309,
    Category: 'Retail',
    Sub_Category: 'Duty-free shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4700,
    MCC_Code: 5300,
    Category: 'Retail',
    Sub_Category: 'Wholesale clubs',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4729,
    MCC_Code: 5271,
    Category: 'Retail',
    Sub_Category: 'Mobile home dealers',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4738,
    MCC_Code: 5262,
    Category: 'Online Marketplaces',
    Sub_Category: '',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4739,
    MCC_Code: 5261,
    Category: 'Retail',
    Sub_Category: 'Lawn and garden supply outlets, including nurseries',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4749,
    MCC_Code: 5251,
    Category: 'Retail',
    Sub_Category: 'Hardware shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4769,
    MCC_Code: 5231,
    Category: 'Retail',
    Sub_Category: 'Glass, paint and wallpaper shops',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4789,
    MCC_Code: 5211,
    Category: 'Retail',
    Sub_Category: 'Lumber and building materials outlets',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4800,
    MCC_Code: 5200,
    Category: 'Retail',
    Sub_Category: 'Home supply warehouse outlets',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4802,
    MCC_Code: 5198,
    Category: 'Retail',
    Sub_Category: 'Paints, varnishes and supplies',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4807,
    MCC_Code: 5193,
    Category: 'Retail',
    Sub_Category: 'Florists supplies, nursery stock and flowers',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4808,
    MCC_Code: 5192,
    Category: 'Retail',
    Sub_Category: 'Books, periodicals and newspapers',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4828,
    MCC_Code: 5172,
    Category: 'Fuel & Gas',
    Sub_Category: 'Petrol/CNG Pump',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4861,
    MCC_Code: 5139,
    Category: 'Retail',
    Sub_Category: 'Commercial footwear',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4863,
    MCC_Code: 5137,
    Category: 'Retail',
    Sub_Category: 'Mens, womens and childrens uniforms and commercial clothing',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4869,
    MCC_Code: 5131,
    Category: 'Retail',
    Sub_Category: 'Piece goods, notions and other dry goods',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4878,
    MCC_Code: 5122,
    Category: 'Retail',
    Sub_Category: 'Drugs, drug proprietors',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4889,
    MCC_Code: 5111,
    Category: 'Retail',
    Sub_Category: 'Stationery, office supplies and printing and writing paper',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4906,
    MCC_Code: 5094,
    Category: 'Retail',
    Sub_Category: 'Precious stones and metals, watches and jewellery',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4926,
    MCC_Code: 5074,
    Category: 'Retail',
    Sub_Category: 'Plumbing and heating equipment and supplies',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4928,
    MCC_Code: 5072,
    Category: 'Retail',
    Sub_Category: 'Hardware equipment and supplies',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4935,
    MCC_Code: 5065,
    Category: 'Retail',
    Sub_Category: 'Electrical parts and equipment',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4949,
    MCC_Code: 5051,
    Category: 'Retail',
    Sub_Category: 'Metal service centres and offices',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4953,
    MCC_Code: 5047,
    Category: 'Retail',
    Sub_Category:
      'Dental/laboratory/medical/ophthalmic hospital equipment and supplies',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4956,
    MCC_Code: 5044,
    Category: 'Retail',
    Sub_Category: 'Office, photographic, photocopy and microfilm equipment',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4979,
    MCC_Code: 5021,
    Category: 'Retail',
    Sub_Category: 'Office and commercial furniture',
    Is_Seller_Accepted: true,
  },
  {
    ID: 4987,
    MCC_Code: 5013,
    Category: 'Retail',
    Sub_Category: 'Motor vehicle supplies and new parts',
    Is_Seller_Accepted: true,
  },
  {
    ID: 5100,
    MCC_Code: 4900,
    Category: 'Fuel & Gas',
    Sub_Category: 'Gas Agency',
    Is_Seller_Accepted: true,
  },
  {
    ID: 5101,
    MCC_Code: 4899,
    Category: 'Utilities',
    Sub_Category: 'Cable and other pay television services',
    Is_Seller_Accepted: true,
  },
  {
    ID: 5171,
    MCC_Code: 4829,
    Category: 'Utilities',
    Sub_Category: 'Wire transfers and money orders',
    Is_Seller_Accepted: true,
  },
  {
    ID: 5184,
    MCC_Code: 4816,
    Category: 'Utilities',
    Sub_Category: 'Computer network/information services',
    Is_Seller_Accepted: true,
  },
  {
    ID: 5186,
    MCC_Code: 4814,
    Category: 'Utilities',
    Sub_Category:
      'Telecommunication services, including local and long distance calls, credit card calls, calls through use of magnetic stripe reading telephones and faxes',
    Is_Seller_Accepted: true,
  },
  {
    ID: 5188,
    MCC_Code: 4812,
    Category: 'Utilities',
    Sub_Category: 'Telecommunication equipment and telephone sales',
    Is_Seller_Accepted: true,
  },
  {
    ID: 5216,
    MCC_Code: 4784,
    Category: 'Transportation',
    Sub_Category: 'Tolls and bridge fees',
    Is_Seller_Accepted: true,
  },
  {
    ID: 5278,
    MCC_Code: 4722,
    Category: 'Travel',
    Sub_Category: 'Travel Agency',
    Is_Seller_Accepted: true,
  },
  {
    ID: 5418,
    MCC_Code: 4582,
    Category: 'Transportation',
    Sub_Category: 'Airports, flying fields and airport terminals',
    Is_Seller_Accepted: true,
  },
  {
    ID: 5489,
    MCC_Code: 4511,
    Category: 'Transportation',
    Sub_Category: 'Airlines and air carriers',
    Is_Seller_Accepted: true,
  },
  {
    ID: 5532,
    MCC_Code: 4468,
    Category: 'Transportation',
    Sub_Category: 'Marinas, marine service and supplies',
    Is_Seller_Accepted: true,
  },
  {
    ID: 5543,
    MCC_Code: 4457,
    Category: 'Transportation',
    Sub_Category: 'Boat rentals and leasing',
    Is_Seller_Accepted: true,
  },
  {
    ID: 5589,
    MCC_Code: 4411,
    Category: 'Transportation',
    Sub_Category: 'Steamships and cruise lines',
    Is_Seller_Accepted: true,
  },
  {
    ID: 5775,
    MCC_Code: 4225,
    Category: 'Transportation',
    Sub_Category:
      'Public warehousing and storage farm products, refrigerated goods and household goods',
    Is_Seller_Accepted: true,
  },
  {
    ID: 5785,
    MCC_Code: 4215,
    Category: 'Transportation',
    Sub_Category: 'Courier services - air and ground and freight forwarders',
    Is_Seller_Accepted: true,
  },
  {
    ID: 5786,
    MCC_Code: 4214,
    Category: 'Transportation',
    Sub_Category:
      'Motor Freight Carriers, Trucking–Local/Long Distance, Moving and Storage Companies, Local Delivery',
    Is_Seller_Accepted: true,
  },
  {
    ID: 5869,
    MCC_Code: 4131,
    Category: 'Transportation',
    Sub_Category: 'Bus Lines',
    Is_Seller_Accepted: true,
  },
  {
    ID: 5879,
    MCC_Code: 4121,
    Category: 'Travel',
    Sub_Category: 'Taxi Cab',
    Is_Seller_Accepted: true,
  },
  {
    ID: 5881,
    MCC_Code: 4119,
    Category: 'Transportation',
    Sub_Category: 'Ambulance Services',
    Is_Seller_Accepted: true,
  },
  {
    ID: 5888,
    MCC_Code: 4112,
    Category: 'Transportation',
    Sub_Category: 'Passenger Railways',
    Is_Seller_Accepted: true,
  },
  {
    ID: 5889,
    MCC_Code: 4111,
    Category: 'Transportation',
    Sub_Category:
      'Transportation–Suburban and Local Commuter Passenger, including Ferries',
    Is_Seller_Accepted: true,
  },
  {
    ID: 5989,
    MCC_Code: 4011,
    Category: 'Transportation',
    Sub_Category: 'Railroads',
    Is_Seller_Accepted: true,
  },
  {
    ID: 7158,
    MCC_Code: 2842,
    Category: 'Contractual Services',
    Sub_Category: 'Speciality cleaning, polishing and sanitation preparations',
    Is_Seller_Accepted: true,
  },
  {
    ID: 7209,
    MCC_Code: 2791,
    Category: 'Contractual Services',
    Sub_Category: 'Typesetting, platemaking and related services',
    Is_Seller_Accepted: true,
  },
  {
    ID: 8229,
    MCC_Code: 1771,
    Category: 'Contractual Services',
    Sub_Category: 'Concrete work contractors',
    Is_Seller_Accepted: true,
  },
  {
    ID: 8239,
    MCC_Code: 1761,
    Category: 'Contractual Services',
    Sub_Category: 'Roofing, siding and sheet metal work contractors',
    Is_Seller_Accepted: true,
  },
  {
    ID: 8250,
    MCC_Code: 1750,
    Category: 'Contractual Services',
    Sub_Category: 'Carpentry contractors',
    Is_Seller_Accepted: true,
  },
  {
    ID: 8260,
    MCC_Code: 1740,
    Category: 'Contractual Services',
    Sub_Category:
      'Masonry, stonework, tile setting, plastering and insulation contractors',
    Is_Seller_Accepted: true,
  },
  {
    ID: 8269,
    MCC_Code: 1731,
    Category: 'Contractual Services',
    Sub_Category: 'Electrical contractors',
    Is_Seller_Accepted: true,
  },
  {
    ID: 8289,
    MCC_Code: 1711,
    Category: 'Contractual Services',
    Sub_Category: 'Heating, plumbing and air-conditioning contractors',
    Is_Seller_Accepted: true,
  },
  {
    ID: 8480,
    MCC_Code: 1520,
    Category: 'Contractual Services',
    Sub_Category: 'General contractors - residential and commercial',
    Is_Seller_Accepted: true,
  },
  {
    ID: 8779,
    MCC_Code: 1221,
    Category: 'NETS',
    Sub_Category: '',
    Is_Seller_Accepted: true,
  },
  {
    ID: 9175,
    MCC_Code: 825,
    Category: 'Agricultural Services',
    Sub_Category: 'Other Agri Inputs',
    Is_Seller_Accepted: true,
  },
  {
    ID: 9176,
    MCC_Code: 824,
    Category: 'Agricultural Services',
    Sub_Category: 'Agricultural Machinery',
    Is_Seller_Accepted: true,
  },
  {
    ID: 9177,
    MCC_Code: 823,
    Category: 'Agricultural Services',
    Sub_Category: 'Farm Equipment',
    Is_Seller_Accepted: true,
  },
  {
    ID: 9178,
    MCC_Code: 822,
    Category: 'Agricultural Services',
    Sub_Category: 'Seeds',
    Is_Seller_Accepted: true,
  },
  {
    ID: 9179,
    MCC_Code: 821,
    Category: 'Agricultural Services',
    Sub_Category: 'Pesticides / Insecticides',
    Is_Seller_Accepted: true,
  },
  {
    ID: 9180,
    MCC_Code: 820,
    Category: 'Agricultural Services',
    Sub_Category: 'Fertilizer Dealers',
    Is_Seller_Accepted: true,
  },
  {
    ID: 9220,
    MCC_Code: 780,
    Category: 'Agricultural Services',
    Sub_Category: 'Landscaping and horticultural services',
    Is_Seller_Accepted: true,
  },
  {
    ID: 9237,
    MCC_Code: 763,
    Category: 'Agricultural Services',
    Sub_Category: 'Agricultural co-operatives',
    Is_Seller_Accepted: true,
  },
  {
    ID: 9256,
    MCC_Code: 744,
    Category: 'Agricultural Services',
    Sub_Category: 'Champagne producers',
    Is_Seller_Accepted: true,
  },
  {
    ID: 9257,
    MCC_Code: 743,
    Category: 'Agricultural Services',
    Sub_Category: 'Wine producers',
    Is_Seller_Accepted: true,
  },
  {
    ID: 9258,
    MCC_Code: 742,
    Category: 'Agricultural Services',
    Sub_Category: 'Veterinary services',
    Is_Seller_Accepted: true,
  },
];

const renderItem = ({item}) => (
  <View style={styles.item}>
    {/* <Text style={styles.idColumn}>{item.ID}</Text> */}
    <Text style={styles.mccCodeColumn}>{item.MCC_Code}</Text>
    <Text style={styles.categoryColumn}>{item.Category}</Text>
    <Text style={styles.subCategoryColumn}>{item.Sub_Category}</Text>
    {/* <Text style={styles.acceptedColumn}>{item.Is_Seller_Accepted.toString()}</Text> */}
  </View>
);

const MCCCodes = ({navigation}) => {

    useFocusEffect(
        useCallback(() => {
          const onBackPress = () => {
            navigation.goBack();
            return true; // Prevent default behavior
          };
    
          BackHandler.addEventListener('hardwareBackPress', onBackPress);
    
          return () => BackHandler.removeEventListener('hardwareBackPress', onBackPress);
        }, [navigation])
      );
    return (
        <View style={styles.container}>
          <View style={styles.headerBar}>
            <Text style={styles.headerBarText}>MCC Codes</Text>
          </View>
          <View style={styles.header}>
            {/* <Text style={styles.idColumn}>ID</Text> */}
            <Text style={styles.mccCodeColumn}>MCC Code</Text>
            <Text style={styles.categoryColumn}>Category</Text>
            <Text style={styles.subCategoryColumn}>Sub-Category</Text>
            {/* <Text style={styles.acceptedColumn}>Accepted</Text> */}
          </View>
          <FlatList
            data={data}
            keyExtractor={item => item.ID.toString()}
            renderItem={renderItem}
            contentContainerStyle={styles.list}
          />
        </View>
      );
};

const styles = StyleSheet.create({
    container: {
      backgroundColor: 'white',
      flex: 1,
    //   padding: 2,
    },
    headerBar: {
      backgroundColor: '#2058BB',
      paddingVertical: 12,
      paddingHorizontal: 8,
      alignItems: 'center',
    },
    headerBarText: {
      color: 'white',
      fontSize: 18,
      fontWeight: '900',
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      backgroundColor: 'white',
      
      paddingVertical: 8,
      paddingHorizontal:7,
    //   paddingHorizontal: 4,
      marginBottom: 0, // Remove space between rows
    },
    idColumn: {
    //   flex: 1,
      fontWeight: 'bold',
      textAlign: 'center',
      width:40,
      paddingHorizontal: 4,
      marginLeft:6,
      borderWidth: 1,
      borderColor: 'gray',
    },
    mccCodeColumn: {
    //   flex: 1,
      fontWeight: 'bold',
      textAlign: 'center',
      width:60,
      paddingHorizontal: 4,
      borderWidth: 1,
      borderColor: 'gray',
    },
    categoryColumn: {
    //   flex: 1,
      fontWeight: 'bold',
      textAlign: 'center',
      width:80,
      paddingHorizontal: 4,
      borderWidth: 1,
      borderColor: 'gray',
    },
    subCategoryColumn: {
      flex: 1,
      fontWeight: 'bold',
      textAlign: 'center',
      paddingHorizontal: 4,
      borderWidth: 1,
      borderColor: 'gray',
    },
    acceptedColumn: {
    //   flex: 1,
      fontWeight: 'bold',
      textAlign: 'center',
      width:70,
      paddingHorizontal: 4,
      marginRight:6,
      borderWidth: 1,
      borderColor: 'gray',
    },
    item: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 0, // Remove space between rows
      paddingHorizontal:7,
     
    },
    text: {
      flex: 1,
      padding: 4,
      fontWeight: 'bold',
      borderWidth: 1,
      borderColor: '#ccc',
      textAlign: 'center',
    },
  });

export default MCCCodes;
